language: r
sudo: required

services:
  - docker

before_install:
- docker build -t markets-shiny .
- docker run --rm -d -p 3838:3838 --name test markets-shiny:latest
- docker ps -a

script:
- docker exec test R -f /srv/shinyapps/app2/run_tests.R

after_script:
- docker rm -f test




