language: generic
sudo: required

services:
  - docker

before_install:
- docker pull mtoto/shiny
- docker build --cache-from mtoto/shiny:latest -t mtoto/shiny . 
- docker run --rm -d -p 3838:3838 --name test mtoto/shiny:latest
- docker ps -a

script:
- docker exec test R -f srv/shiny-server/myapp/run_tests.R

after_script:
- docker rm -f test




